// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    get: function(path, callback) {
      var xhr;
      xhr = new XMLHttpRequest;
      xhr.open('GET', '/ds-api/#{path}/', true);
      xhr.onload = function() {
        callback(null, xhr.response);
      };
      xhr.onerror = function(e) {
        var err;
        err = 'Request failed : #{e.target.status}';
        callback(err);
      };
      xhr.setRequestHeader('Content-Type', 'application/json');
      return xhr.send();
    },
    post: function(path, callback) {
      var location, xhr;
      location = window.location;
      xhr = new XMLHttpRequest;
      xhr.open('POST', "/ds-api/" + path, true);
      xhr.onload = function() {
        callback(null, xhr.response);
      };
      xhr.onerror = function(e) {
        var err;
        err = 'Request failed : #{e.target.status}';
        callback(err);
      };
      return window.addEventListener('message', (function(event) {
        var intent, requestHeader;
        intent = event.data;
        xhr.setRequestHeader('Content-Type', 'application/json');
        requestHeader = 'Basic ' + btoa(intent.appName + ":" + intent.token);
        xhr.setRequestHeader('Authorization', requestHeader);
        xhr.send(JSON.stringify(attributes));
      }), true);
    }
  };

}).call(this);
